Code quality
rupertford/melody pull request #13
Opened 2017-02-06 23:02 UTC by rupertford

All python is now pep8 compliant and is mostly pylint compliant. landscape reports 96%. Remaining pylint issues are:

src/inputs.py
R:113, 4: Too many arguments (6/5) (too-many-arguments)
I'm happy with the number of arguments in this piece of code.
C:159,12: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
I'm happy using range and len.

examples/PSyclone/psyclone.py
R:104, 4: Too many arguments (6/5) (too-many-arguments)
I'm happy with the number of arguments in this piece of code.
W:113,16: Access to a protected member _validate of a client class (protected-access)
This would require a change to a remote code, not one in this repository, so this error depends on external factors.

examples/shallow/execute.py
R: 40, 0: Too many local variables (18/15) (too-many-locals)
I'm happy with the number of variables in this piece of code (and the code will change in the future in any case)

landscape gives some errors that are not issues for pylint and pep8. For example it complains about the use of "_" and the variable not being used. I am not planning to change this as this is an accepted convention.

2017-02-07 10:10 UTC, arporter commented on examples/PSyclone/psyclone.py
> +        for invoke in self._psy.invokes.invoke_list:
`psy` could be None which would case this code to fail.

2017-02-07 10:17 UTC, arporter commented on examples/PSyclone/psyclone.py
>              exit(1)
Should we raise an Exception here rather than just `exit()`?

2017-02-07 10:18 UTC, arporter commented on examples/PSyclone/psyclone.py
> +        '''Returns the name of the melody input class '''
Inconsistent white space in doc string (picky!)

2017-02-07 10:19 UTC, arporter commented on examples/PSyclone/psyclone.py
> +FILE = ("/home/rupert/proj/GungHoSVN/PSyclone_trunk/examples/"
Code uses a file that is not part of this project. I suggest copying that file into melody/examples.

2017-02-07 10:25 UTC, arporter commented on examples/shallow/execute.py
> +    base_path = "/home/rupert/proj/GOcean/shallow_benchmark/original"
Again, have a hard-wired path to GOcean code that is not a part of this project. I suggest adding a comment on where to get the GOcean code from and a variable to hold the path to its location on disk.

2017-02-07 10:28 UTC, arporter commented on src/melody/inputs.py
> +        '''Returns the state variable. This is False by default.'''
How can a state be `False`? Should this be named something like `requires_state` instead or, if it is intended to hold a state object, maybe it should be None by default? (None is 'falsey' in python anyway so we keep that functionality if it is used anywhere.)

2017-02-07 10:30 UTC, arporter commented on src/melody/inputs.py
> +        '''We work out all combinations using this internal recursion class'''
should that be "internal recusion method"?

2017-02-07 10:32 UTC, arporter requested changes
Generally good and I'm happy with what pep8 and pylint report. I've taken the opportunity to have a closer look at the lines of code involved in this merge request and have requested some changes - see the in-line comments/questions.

2017-02-07 23:33 UTC, rupertford commented on examples/PSyclone/psyclone.py
> +        for invoke in self._psy.invokes.invoke_list:
Quite right. I've made psy a required argument. Note this code is all subject to change as it is not working correctly at the moment so I've not bothered too much about being graceful with errors.

2017-02-07 23:37 UTC, rupertford commented on examples/PSyclone/psyclone.py
>              exit(1)
Again, this code does not currently work so I've not spent much time on its niceties. However, I've made it raise a RuntimeError exception.

2017-02-07 23:39 UTC, rupertford commented on examples/PSyclone/psyclone.py
> +        '''Returns the name of the melody input class '''
Nothing wrong with looking for consistency. I've removed the extra white space.

2017-02-07 23:48 UTC, rupertford commented on examples/PSyclone/psyclone.py
> +FILE = ("/home/rupert/proj/GungHoSVN/PSyclone_trunk/examples/"
OK, I've done this.

2017-02-08 00:06 UTC, rupertford commented on examples/shallow/execute.py
> +    base_path = "/home/rupert/proj/GOcean/shallow_benchmark/original"
I've added the required benchmark code to the repository for the time being. I've tested it and it runs OK.

2017-02-08 00:09 UTC, rupertford commented on src/melody/inputs.py
> +        '''Returns the state variable. This is False by default.'''
Agreed. I've set the default value to False and changed the documentation.

2017-02-08 00:10 UTC, rupertford commented on src/melody/inputs.py
> +        '''We work out all combinations using this internal recursion class'''
Yes. Changed.

2017-02-08 00:24 UTC, rupertford commented
OK, suggested changes made. Ready for 2nd review. Note I also removed an additional warning that landscape brought up which was missed by my version of pylint.

2017-02-08 09:53 UTC, arporter approved these changes
Requested changes have been made. I didn't actually intend for you to import the GOcean code into melody but we can always change that later. Maybe we should move GOcean over to some git repo and then it could be done via submodules.

2017-02-08 13:55 UTC, jimboid commented
This is the one I was just talking about Rupert.

2017-02-08 14:56 UTC, merged