ticket #2. Examples now work.
rupertford/melody pull request #3
Opened 2017-01-31 17:35 UTC by rupertford

The examples, other than PSyclone (which is under development) now work. To test, set you Python path to the src directory, then run one of the examples e.g. cd examples/longbow_gromacs; python ./gromacs.py. You should see a list of outputs representing all options specified in the Python input file.

2017-02-01 09:22 UTC, arporter commented
Not sure exactly what you'd like me to review :-)
Just the commits under this issue presumably?

2017-02-01 09:29 UTC, arporter commented on src/melody/inputs.py
> +class Base(object):
I don't think 'Base' is a good name for a class :-) How about InputBase or just Input?

2017-02-01 09:34 UTC, arporter requested changes
I can run the gromacs example without problems.

Please add doc-strings and comments to the code touched in this issue!
Otherwise, I think it looks fine (I'm not going to try and understand everything here).

2017-02-02 11:48 UTC, rupertford commented
I've changed the class name as (correctly) suggested. I've made a separate ticket to make the code fully pep8 and (reasonably) pylint compliant which will include adding doc strings throughout the source. So, can you skip that part of the review for the timebeing - pretty please.

2017-02-03 12:07 UTC, arporter approved these changes
Base class name has been changed to Input - good.
All OK.

2017-02-03 21:48 UTC, rupertford commented
Merging to Master

2017-02-03 21:49 UTC, merged